name: Docker Image CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 1 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        major: [ 1.21 ]
        os: [ bullseye-slim ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set variables
        id: vars
        working-directory: ${{ matrix.major }}/${{ matrix.os }}
        run: |
          echo "repository=${GITHUB_ACTOR}/$(basename ${GITHUB_REPOSITORY})" >> $GITHUB_OUTPUT
          echo "version=$(grep 'RESTY_VERSION ' Dockerfile | awk '{print $3}')" >> $GITHUB_OUTPUT
          echo "workdir=${{ matrix.major }}/${{ matrix.os }}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Copy files
        run: |
          cp files/*.conf ${{ matrix.major }}/${{ matrix.os }}/
          tree .
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ steps.vars.outputs.workdir }}
          pull: true
          push: true
          platforms: linux/amd64
          tags: |
            ${{ steps.vars.outputs.repository }}:${{ matrix.major }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.version }}
            ${{ steps.vars.outputs.repository }}:${{ matrix.major }}-${{ matrix.os }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.version }}-${{ matrix.os }}
